config/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url, static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from apps.quiz.views import graph

from config.utils import easy_url as easy
from config import settings

admin.autodiscover()

urlpatterns = patterns('',
    #main
    url(r'^$', 'config.views.landing', name='landing'),
    url(easy('^index/'), 'config.views.index', name='index'),
)

# header links
urlpatterns += (
    url(easy('^hizliokuma_nedir/'),     'config.views.hizliokuma_nedir',    name='hizliokuma_nedir'),
    url(easy('^egitim_sistemi/'),       'config.views.egitim_sistemi',      name='egitim_sistemi'),
)

urlpatterns += (
    # tachistoscope
    url(easy('^practices/tachistoscope/'),           'apps.practices.views.tachistoscope',           name='tachistoscope'),
    url(easy('^practices/tachistoscope/:level/'),    'apps.practices.views.tachistoscope',           name='tachistoscope_detail'),
    # env_focus
    url(easy('^practices/env_focus/'),            'apps.practices.views.env_focus',   name='env_focus'),
    url(easy('^practices/env_focus/:level/'),     'apps.practices.views.env_focus',   name='env_focus_detail'),
    # shadowing
    url(easy('^practices/shadowing/'),                      'apps.practices.views.shadowing',             name='shadowing'),
    url(easy('^practices/shadowing/:category_id/'),         'apps.practices.views.shadowing',             name='shadowing_category'),
    url(easy('^practices/shadowing_detail/:article_id/'),   'apps.practices.views.shadowing_detail',      name='shadowing_detail'),
    # grouping
    url(easy('^practices/grouping/'),                     'apps.practices.views.grouping',                name='grouping'),
    url(easy('^practices/grouping/:category_id/'),        'apps.practices.views.grouping',                name='grouping_category'),
    url(easy('^practices/grouping_detail/:article_id/'),  'apps.practices.views.grouping_detail',         name='grouping_detail'),
    # multi_focus
    url(easy('^practices/multi_focus/'),              'apps.practices.views.multi_focus', name='multi_focus'),
    url(easy('^practices/multi_focus/:level/'),       'apps.practices.views.multi_focus', name='multi_focus_detail'),
    # block_reading
    url(easy('^practices/block_reading/'),                        'apps.practices.views.block_reading',           name='block_reading'),
    url(easy('^practices/block_reading/:category_id/'),           'apps.practices.views.block_reading',           name='block_reading_category'),
    url(easy('^practices/block_reading_detail/:article_id/'),     'apps.practices.views.block_reading_detail',    name='block_reading_detail'),
    # eye_focusing
    url(easy('^practices/eye_focusing/'),            'apps.practices.views.eye_focusing',            name='eye_focusing'),
    url(easy('^practices/eye_focusing/:level/'),     'apps.practices.views.eye_focusing',            name='eye_focusing_detail'),

    # eye_muscle_development
    url(easy('^practices/eye_muscle_development/'),  'apps.practices.views.eye_muscle_development', name='eye_muscle_development'),

    # speed_reading
    url(easy('^quiz/'),                         'apps.quiz.views.category', name='quiz'),
    url(easy('^quiz/category/:category_id/'),   'apps.quiz.views.test', name='quiz_cat'),
    url(easy('^quiz/detail/:test_id/'),         'apps.quiz.views.detail', name='quiz_test'),
    url(easy('^quiz/questions/:test_id/'),      'apps.quiz.views.questions', name='quiz_questions'),
    url(easy('^quiz/result/'),                  'apps.quiz.views.result', name='quiz_result'),

    # Quiz Users
    url(easy('^exam/'), 'apps.exam.views.categories', name='exam'),
    url(easy('^exam/:category_id/'), 'apps.exam.views.categories', name='exam_category'),
    url(easy('^exam_detail/:exam_id/'), 'apps.exam.views.detail', name='exam_detail'),

    # HomeWork
    url(easy('^homework/'),          'apps.homework.views.homework_index',   name='homework_index'),
    url(easy('^homework/:day/'),     'apps.homework.views.homework_day',     name='homework_day'),
    url(easy('^homework_user'),      'apps.homework.views.user_works',       name='homework_user'),
    url(easy('^homework_done/:id/'), 'apps.homework.views.done',             name='homework_done'),

    # Presentations
    url(easy('^presentations/'), 'apps.presentations.views.index', name='presentations'),

    # performance
    url(easy('^practices/performance/'),             'apps.practices.views.performance', name='performance'),
    url(easy('^practices/performance/:event_type/'), 'apps.practices.views.performance', name='performance'),


    url(easy('^practices/record_time/:event_type/'), 'apps.practices.views.record_time', name='record_time'),
)

# api
urlpatterns += (
    url(easy('^api/get_articles/'),                             'config.api.get_articles',      name="api_get_articles"),
    url(easy('^api/stats/:status/:stat_type/'),                 'apps.practices.views.stats',   name='api_stats'),
    url(easy('^api/test_read_finish/:total_time/:word_count/'), 'apps.quiz.views.finish',       name='api_test_read_finish'),
    url(easy('^api/test_graph/'),                               'apps.quiz.views.graph',      name='api_test_graph'),
)

# Authentication
urlpatterns += (
    url(r'^admin/', include(admin.site.urls)),
    url(easy('^accounts/login/'), 'apps.profiles.views.auth_login', name='login'),
    url(easy('^accounts/logout/'), 'apps.profiles.views.auth_logout', name='logout'),
    url(easy('^accounts/disabled/'), 'apps.profiles.views.disabled_account', name='disabled_account'),
    url(easy('^accounts/change_password/'), 'apps.profiles.views.change_password', name='change_password'),
)

# Media Urls
urlpatterns += (
    static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

apps/quiz/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from config.constants import LANG_CHOICES, TYPE_CHOICES


class QuizCategoryModel(models.Model):
    lang = models.CharField('Dil', max_length=255, choices=LANG_CHOICES, default='tr')
    type = models.CharField('Öğrenci Tipi', max_length=255, choices=TYPE_CHOICES, default='y')
    title = models.CharField(max_length=255, verbose_name=u'Kategori')

    class Meta:
        verbose_name = u'Test Kategorisi'
        verbose_name_plural = u'Test Kategorileri'


    def __unicode__(self):
        return u'{0} - {1} - {2}'.format(self.get_lang_display(), self.get_type_display(), self.title)


class QuizModel(models.Model):

    STATUS_CHOICES = (
        ('draft', u'Taslak'),
        ('public', u'Görünür'),
        ('closed', u'Görünmez'),
    )

    title = models.CharField(verbose_name=u'Test Başlığı', max_length=255)
    text = models.TextField(verbose_name=u'Metin', blank=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=10, verbose_name=u'Durumu')
    categories = models.ManyToManyField(QuizCategoryModel, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = u'Test'
        verbose_name_plural = u'Testler'

        ordering = ('-id',)

    def __unicode__(self):
        return u'%s' % self.title

    @property
    def question_count(self):
        return QuizQuestionModel.objects.filter(quiz=self).count()

    @property
    def is_published(self):
        if self.status is 'public':
            return True


class QuizQuestionModel(models.Model):
    quiz = models.ForeignKey(QuizModel, verbose_name=u'Test')
    question = models.TextField(verbose_name=u'Soru')

    class Meta:
        verbose_name = u'Soru'
        verbose_name_plural = u'Sorular'


class QuizAnswerModel(models.Model):
    question = models.ForeignKey(QuizQuestionModel)
    answer = models.CharField(max_length=255, verbose_name=u'Cevap')
    status = models.BooleanField(default=False, verbose_name=u'Doğru mu ?')

    class Meta:
        verbose_name = u'Cevap'
        verbose_name_plural = u'Cevaplar'


    def __unicode__(self):
        return u'%s' % self.answer


class QuizScoreModel(models.Model):
    profile = models.ForeignKey(User, verbose_name=u'Kullanıcı')
    quiz = models.ForeignKey(QuizModel, verbose_name=u'Test')
    correct_answers = models.IntegerField(default=0, verbose_name=u'Doğru cevap sayısı')
    date = models.DateTimeField(verbose_name=u'Tarih')
    reading_speed = models.IntegerField(verbose_name='Okuma Hızı')

    class Meta:
        verbose_name = u'Sonuç'
        verbose_name_plural = u'Sonuçlar'
        ordering = ['-id',]

    @property
    def total_question(self):
        return self.quiz.question_count

    def __unicode__(self):
        return u'%s - %s' % (self.profile, self.quiz)

apps/exam/views.py
from annoying.decorators import render_to
from django.contrib.auth.decorators import login_required
from apps.quiz.models import *


@login_required
@render_to('exam/categories.html')
def categories(request, category_id=None):
    cats = QuizCategoryModel.objects.filter(type='s')

    if category_id:
        articles = QuizModel.objects.filter(categories__id=category_id)

        return {
            'categories': cats,
            'articles': articles
        }
    else:
        return {
            'categories': cats
        }


@login_required
@render_to('exam/detail.html')
def detail(request, exam_id):
    questions = QuizQuestionModel.objects.filter(quiz__id=exam_id)
    return {
        'questions': questions,
        'test_id' : exam_id
    }

templates/exam/categories.html
{% extends "index.html" %}

    {% block pageID %}shadowing{% endblock %}

    {% block content %}
    {{ block.super }}


        <div class="well span8 game-area">


            <div id="gameArea" class="clearfix">
                <div class="text-categories span2">
                    {% for category in categories %}
                        <a href="{% url 'exam_category' category.id %}" class="btn btn-block">{{ category.title }}</a>
                    {% endfor %}
                </div>

                <div class="article-list span6 white-cell">
                    <ul class="nav nav-list text-selection">
                    {% if articles %}
                        {% for article in articles %}
                            <li><a href="{% url 'exam_detail' article.id %}">{{ article.title }}</a></li>
                        {% endfor %}
                    {% else %}
                        <li><a href="#">Önce Bir Kategori Seçiniz</a></li>
                    {% endif %}
                    </ul>
                </div>
            </div>
        </div>



    {% endblock content %}

templates/exam/detail.html
{% extends "index.html" %}

    {% block pageID %}exam_detail{% endblock %}

    {% block content %}
    {{ block.super }}

        <div class="well span8 game-area">


            <form action="{% url 'quiz_result' %}" method="POST">
            {% csrf_token %}

            <input type="hidden" value="{{ test_id }}" name="test_id"/>
            <input type="hidden" value="" name="ms"/>
            <input type="hidden" value="" name="total_ms"/>
            <input type="hidden" value="" name="word_count"/>

            <div id="gameArea" class="span8 dpan5">
            {% for question in questions %}
                <div class="testQuestion">
                    <div class="question">
                        {{ question.question|safe|linebreaksbr }}
                    </div>
                    <hr>
                    <ul class="answers">
                        {% for answer in question.quizanswermodel_set.all %}
                            <li>
                                <label class="radio">
                                    <input type="radio" name="{{ question.id }}" value="{{ answer.id }}">
                                    {# TODO: status u kaldir #}
                                    {# {% if answer.status %}> {% endif %} #}
                                    {{ answer.answer }}
                                </label>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
            <div id="overlay"></div>
            </div>
            <div class="bottom-buttons span8 pull-span">
                <hr>
                <div class="btn-group pull-right">
                    <a href="#" class="btn btn-success start">Başlat </a>
                </div>
            </div>
            </form>

        </div>

    {% endblock content %}